---
development:
  cloud_name: hdqw2b8hv
  api_key: '679352867853935'
  api_secret: DYg4F5heFnshvffk6QpEcCqpZVI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hdqw2b8hv
  api_key: '679352867853935'
  api_secret: DYg4F5heFnshvffk6QpEcCqpZVI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hdqw2b8hv
  api_key: '679352867853935'
  api_secret: DYg4F5heFnshvffk6QpEcCqpZVI
  enhance_image_tag: true
  static_image_support: false
